spring:
  application:
    name: Health Tracker API

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:mymongodb}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

app:
  frontend:
    redirect-uri: ${FRONTEND_REDIRECT_URI:http://localhost:3000/oauth2/redirect}
    origin: ${FRONTEND_ORIGIN:http://localhost:3000}